apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: selfkey-api
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs: 
        NODE_ENV: production
profiles:
- name: dev
  build:
    artifacts:
    - image: selfkey-api
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          NODE_ENV: development
      sync:
        infer:
        - "**/*"
  activation:
    - command: dev
  deploy:
    kubeContext: docker-desktop
    helm:
      flags:
        upgrade:
        - --install
      releases:
        - name: selfkey-api-dev
          chartPath: ./charts/selfkey-api
          artifactOverrides:
            image: selfkey-api
          overrides:
            service:
              type: NodePort
              port: 3000
            command:
              - "yarn"
            args:
              - "dev"