apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: asia.gcr.io/selfkey2/selfkey-api
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs: 
        NODE_ENV: production
  local:
    push: true
profiles:
- name: dev
  build:
    local:
      push: false
    artifacts:
    - image: selfkey-api
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          NODE_ENV: development
      sync:
        infer:
        - "**/*"
  activation:
    - command: dev
  deploy:
    kubeContext: docker-desktop
    helm:
      releases:
        - name: selfkey-api-dev
          chartPath: ./charts/selfkey-api
          remote: false
          artifactOverrides:
            image: selfkey-api
          overrides:
            service:
              type: NodePort
              port: 3000
            command:
              - "yarn"
            args:
              - "start-dev"
- name: run
  build:
    local:
      push: false
    artifacts:
    - image: asia.gcr.io/selfkey2/selfkey-api
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          NODE_ENV: production
  activation:
    - command: run
    - command: delete
  deploy:
    kubeContext: docker-desktop
    helm:
      releases:
        - name: selfkey-api-local-prod
          chartPath: ./charts/selfkey-api
          remote: false
          artifactOverrides:
            image: asia.gcr.io/selfkey2/selfkey-api
          overrides:
            service:
              type: NodePort
              port: 3000
            command:
              - "yarn"
            args:
              - "start"