version: 2.1

orbs:
  docker: circleci/docker@1.3.0
jobs:
  build-and-push:
    executor: docker/docker
    context: google-container-registry
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: login to docker repository
          command: |
            docker login -u ${GCR_DOCKER_USERNAME} -p ${GCR_DOCKER_PASSWORD} ${GCR_DOCKER_REPOSITORY}
      - run:
          name: install skaffold
          command: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/1.12.1/skaffold-linux-amd64
            chmod +x skaffold
            sudo mv skaffold /usr/local/bin
      - run:
          name: build
          command: |
            skaffold build -p circleci
workflows:
  main:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
                - dev
